apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bcs-bot-ingress
  namespace: bcs-bot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bcs-bot.eastus2.cloudapp.azure.com
      secretName: bcs-bot-tls
  rules:
    - host: bcs-bot.eastus2.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bcs-bot-svc
                port:
                  number: 80
